framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(default:default_uri:DEFAULT_URI)%'

parameters:
    default_uri: 'http://localhost'

when@prod:
    framework:
        router:
            strict_requirements: null
